apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-monitoring-secret
  namespace: k8s-monitoring
spec:
  # 5분마다 Vault에서 secret 동기화
  refreshInterval: 5m

  # ClusterSecretStore 참조
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore

  # 생성될 K8s Secret 설정
  target:
    name: k8s-monitoring-secret
    creationPolicy: Owner

  # OCI Vault에서 가져올 secret 정보
  data:
  - secretKey: SLACK_TOKEN
    remoteRef:
      # TODO: OCI Vault에 slack token을 저장한 후 해당 secret name으로 변경
      key: k8s-monitoring-slack-token
