apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-monitoring-secret
  namespace: k8s-monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: k8s-monitoring-secret
    creationPolicy: Owner
    template:
      data:
        DISCORD_BOT_TOKEN: '{{ .raw | fromJson | dig "DISCORD_BOT_TOKEN" "" }}'
        DISCORD_DEFAULT_CHANNEL_ID: '{{ .raw | fromJson | dig "DISCORD_DEFAULT_CHANNEL_ID" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: k8s-monitoring
