apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-monitoring-secret
  namespace: k8s-monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: k8s-monitoring-secret
    creationPolicy: Owner
  data:
  - secretKey: SLACK_TOKEN
    remoteRef:
      key: truffle-token
