apiVersion: batch/v1
kind: CronJob
metadata:
  name: hangsha-crawler
  labels:
    app: hangsha-crawler
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */3 * * *" # 3시간 간격
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: hangsha-crawler-dev
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/hangsha-dev/hangsha-batch:9
              name: hangsha-crawler
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 1Gi
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
      
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hangsha-crawler-dev
