apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hangsha-api.yaml
- hangsha-crawler.yaml
- hangsha-kiwi.yaml
- hangsha-manticore.yaml
- hangsha-valkey.yaml

images:
- name: yny.ocir.io/ax1dvc8vmenm/hangsha-dev/hangsha-batch
  newTag: "74"
- name: yny.ocir.io/ax1dvc8vmenm/hangsha-dev/hangsha-kiwi
  newTag: "1"
- name: yny.ocir.io/ax1dvc8vmenm/hangsha-dev/hangsha-server
  newTag: "74"
