apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: siksha-prod
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: siksha-prod
    creationPolicy: Owner
    template:
      data:
        SPRING_DATASOURCE_URL: '{{ .raw | fromJson | dig "spring.datasource.url" "" }}'
        SPRING_DATASOURCE_USERNAME: '{{ .raw | fromJson | dig "spring.datasource.username" "" }}'
        SPRING_DATASOURCE_PASSWORD: '{{ .raw | fromJson | dig "spring.datasource.password" "" }}'
        JWT_SECRET_KEY: '{{ .raw | fromJson | dig "jwt.secret-key" "" }}'
        SPRING_CLOUD_AWS_S3_BUCKET: '{{ .raw | fromJson | dig "spring.cloud.aws.s3.bucket" "" }}'
        SPRING_DATA_REDIS_HOST: '{{ .raw | fromJson | dig "spring.data.redis.host" "" }}'
        SPRING_DATA_REDIS_PORT: '{{ .raw | fromJson | dig "spring.data.redis.port" "" }}'
        SIKSHA_BANNED_WORDS: '{{ .raw | fromJson | dig "siksha.banned.words" "" }}'
        SIKSHA_OAUTH_GOOGLE_CLIENT_ID_ANDROID: '{{ .raw | fromJson | dig "siksha.oauth.google.client-id.android" "" }}'
        SIKSHA_OAUTH_GOOGLE_CLIENT_ID_IOS_PROD: '{{ .raw | fromJson | dig "siksha.oauth.google.client-id.ios-prod" "" }}'
        SIKSHA_OAUTH_GOOGLE_CLIENT_ID_IOS_DEV: '{{ .raw | fromJson | dig "siksha.oauth.google.client-id.ios-dev" "" }}'
        SIKSHA_OAUTH_GOOGLE_CLIENT_ID_WEB_PROD: '{{ .raw | fromJson | dig "siksha.oauth.google.client-id.web-prod" "" }}'
        SIKSHA_OAUTH_GOOGLE_CLIENT_ID_WEB_DEV: '{{ .raw | fromJson | dig "siksha.oauth.google.client-id.web-dev" "" }}'
        SIKSHA_OAUTH_KAKAO_APP_ID: '{{ .raw | fromJson | dig "siksha.oauth.kakao.app-id" "" }}'
        SIKSHA_OAUTH_APPLE_APPROVED_AUDIENCE: '{{ .raw | fromJson | dig "siksha.oauth.apple.approved-audience" "" }}'
        SLACK_TOKEN: '{{ .raw | fromJson | dig "slack.token" "" }}'
        SLACK_CHANNEL: '{{ .raw | fromJson | dig "slack.channel" "" }}'
        SIKSHA_FIREBASE_SERVICE_ACCOUNT: '{{ .raw | fromJson | dig "siksha.firebase.service-account" "" }}'
        SIKSHA_CRAWLER_API_KEY: '{{ .raw | fromJson | dig "siksha.crawler.api-key" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: siksha-prod