apiVersion: batch/v1
kind: CronJob
metadata:
  name: siksha-crawler
  labels:
    app: siksha-crawler
spec:
  concurrencyPolicy: Forbid
  schedule: "0 20 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: siksha
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/siksha-prod/siksha-crawler
              name: siksha-crawler
