apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: pupuri
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: pupuri
  destination:
    name: in-cluster
    namespace: pupuri-prod
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/pupuri-prod
    directory:
      include: 'pupuri-*.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
