apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: waffice-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: waffice-dev
    creationPolicy: Owner
    template:
      data:
        username: '{{ .raw | fromJson | dig "username" "" }}'
        password: '{{ .raw | fromJson | dig "password" "" }}'
        host: '{{ .raw | fromJson | dig "host" "" }}'
        port: '{{ .raw | fromJson | dig "port" "" }}'
        dbname: '{{ .raw | fromJson | dig "dbname" "" }}'
        GOOGLE_CLIENT_ID: '{{ .raw | fromJson | dig "GOOGLE_CLIENT_ID" "" }}'
        GOOGLE_CLIENT_SECRET: '{{ .raw | fromJson | dig "GOOGLE_CLIENT_SECRET" "" }}'
        FRONTEND_ORIGIN: '{{ .raw | fromJson | dig "FRONTEND_ORIGIN" "" }}'
        APP_SECRET_KEY: '{{ .raw | fromJson | dig "APP_SECRET_KEY" "" }}'
        JWT_SECRET_KEY: '{{ .raw | fromJson | dig "JWT_SECRET_KEY" "" }}'
        JWT_EXPIRE_HOURS: '{{ .raw | fromJson | dig "JWT_EXPIRE_HOURS" "" }}'
        email_compartment_id: '{{ .raw | fromJson | dig "email_compartment_id" "" }}'
        email_from_email: '{{ .raw | fromJson | dig "email_from_email" "" }}'
        email_from_name: '{{ .raw | fromJson | dig "email_from_name" "" }}'
        email_reply_to: '{{ .raw | fromJson | dig "email_reply_to" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: waffice-dev
