apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-prod
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: n8n-prod
    creationPolicy: Owner
    template:
      data:
        N8N_ENCRYPTION_KEY: '{{ .raw | fromJson | dig "encryption-key" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: n8n-prod
