apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: snutt-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: snutt-dev
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/snutt-dev
    directory:
      include: 'snutt-*.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
