apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- snutt-secret.yaml
- snutt-valkey.yaml
- snutt-data-service-account.yaml
- snutt-api.yaml
- snutt-batch.yaml
images:
- name: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-api
  newTag: d40d9bb9211b
- name: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-batch
  newTag: d40d9bb9211b
