apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-ev-batch-lecture-sync-latest-semester
  labels:
    app: snutt-ev-batch-lecture-sync-latest-semester
spec:
  concurrencyPolicy: Forbid
  schedule: "10 */12 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: snutt
          volumes:
            - name: oci-api-key
              secret:
                secretName: oci-api-key
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-ev-batch:82
              name: snutt-ev-batch-lecture-sync-latest-semester
              volumeMounts:
                - name: oci-api-key
                  mountPath: /root/.oci
                  readOnly: true
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
                limits:
                  cpu: 1000m
                  memory: 2Gi
              env:
                - name: JOB_NAME
                  value: "NEXT_SEMESTER_SYNC_JOB"
                - name: JAVA_OPTS
                  value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -Duser.timezone=UTC"
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
                - name: TRUFFLE_ENABLED
                  value: "true"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-ev-batch-lecture-sync-all
  labels:
    app: snutt-ev-batch-lecture-sync-all
spec:
  concurrencyPolicy: Forbid
  # 실행 방법
  # kubectl create job snutt-ev-batch-snuev-migration --from=cronjob/snutt-ev-batch-snuev-migration
  schedule: "0 0 31 2 *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: snutt
          volumes:
            - name: oci-api-key
              secret:
                secretName: oci-api-key
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-ev-batch:82
              name: snutt-ev-batch-lecture-sync-all
              volumeMounts:
                - name: oci-api-key
                  mountPath: /root/.oci
                  readOnly: true
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
                limits:
                  cpu: 1000m
                  memory: 2Gi
              env:
                - name: JOB_NAME
                  value: "SYNC_JOB"
                - name: JAVA_OPTS
                  value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -Duser.timezone=UTC"
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
                - name: TRUFFLE_ENABLED
                  value: "true"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-ev-batch-snuev-migration
  labels:
    app: snutt-ev-batch-snuev-migration
spec:
  concurrencyPolicy: Forbid
  suspend: true
  # 실행 방법
  # kubectl create job snutt-ev-batch-snuev-migration --from=cronjob/snutt-ev-batch-snuev-migration
  schedule: "0 0 31 2 *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: snutt
          volumes:
            - name: oci-api-key
              secret:
                secretName: oci-api-key
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-ev-batch:82
              imagePullPolicy: IfNotPresent
              name: snutt-ev-batch-snuev-migration
              volumeMounts:
                - name: oci-api-key
                  mountPath: /root/.oci
                  readOnly: true
              resources:
                requests:
                  cpu: 200m
                  memory: 1Gi
                limits:
                  cpu: 1000m
                  memory: 1Gi
              env:
                - name: JOB_NAME
                  value: "SNUEV_MIGRATION_JOB"
                - name: JAVA_OPTS
                  value: "-XX:InitialRAMPercentage=80.0 -XX:MaxRAMPercentage=80.0 -Duser.timezone=UTC"
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
                - name: TRUFFLE_ENABLED
                  value: "true"
