apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snutt-v2
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: snutt-v2
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: snutt-v2-dev
