apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: snutt-valkey-dev
  labels:
    app: snutt-valkey-dev
spec:
  serviceName: snutt-valkey-dev
  replicas: 1
  selector:
    matchLabels:
      app: snutt-valkey-dev
  template:
    metadata:
      labels:
        app: snutt-valkey-dev
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:8-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: valkey-data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: valkey-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: snutt-valkey-dev
spec:
  type: ClusterIP
  selector:
    app: snutt-valkey-dev
  ports:
    - port: 6379
      targetPort: 6379
