apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocir-pull-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: ocir-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        # OCI provider uses GetSecretBundleByName; this must be the Vault secret name.
        key: ocir-dockerconfig
