apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: snutt-timetable-batch
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: snutt
  destination:
    name: in-cluster
    namespace: snutt-prod
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/snutt-prod/snutt-timetable-batch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
