apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: loki
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: loki
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 7.3.0
    helm:
      releaseName: loki
      valueFiles:
      - $values/argocd/loki/values.yaml
  - repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/loki
    directory:
      include: '{resources.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
