apiVersion: batch/v1
kind: CronJob
metadata:
  name: hangsha-crawler
  labels:
    app: hangsha-crawler
spec:
  concurrencyPolicy: Forbid
  schedule: "0 */3 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: hangsha-crawler-prod
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/hangsha-prod/hangsha-batch:5
              name: hangsha-crawler
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 1Gi
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "prod"
                - name: MANTICORE_BASE_URL
                  value: "http://hangsha-manticore:9308"
                - name: KIWI_BASE_URL
                  value: "http://hangsha-kiwi:8090"
                # TODO: hangsha-valkey replicas를 1로 변경할 때 주석 해제하기
                # - name: SPRING_DATA_REDIS_HOST
                #   value: "hangsha-valkey"
                # - name: SPRING_DATA_REDIS_PORT
                #   value: "6379"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hangsha-crawler-prod
