apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- hangsha-api.yaml
- hangsha-crawler.yaml
- hangsha-kiwi.yaml
- hangsha-manticore.yaml
- hangsha-valkey.yaml

images:
- name: yny.ocir.io/ax1dvc8vmenm/hangsha-prod/hangsha-batch
  newTag: "8"
- name: yny.ocir.io/ax1dvc8vmenm/hangsha-prod/hangsha-kiwi
  newTag: "1"
- name: yny.ocir.io/ax1dvc8vmenm/hangsha-prod/hangsha-server
  newTag: "8"
