apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: discord-bot
    creationPolicy: Owner
    template:
      data:
        token: '{{ .raw | fromJson | dig "token" "" }}'
        announce_channel_id: '{{ .raw | fromJson | dig "announce_channel_id" "" }}'
        n8n_token: '{{ .raw | fromJson | dig "n8n_token" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: discord-bot
