apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: discord-bot
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: discord-bot
