apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- discord-bot.yaml
- discord-bot-secret.yaml

images:
- name: yny.ocir.io/ax1dvc8vmenm/discord-bot
  newTag: 856a023f352451acacd247f68be5d03890c9a3af
