apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- discord-bot.yaml
- discord-bot-secret.yaml

images:
- name: yny.ocir.io/ax1dvc8vmenm/discord-bot
  newTag: 16cf3fb6c9611f6c038fb977e93d6880a48d356d
