apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- discord-bot.yaml
- discord-bot-secret.yaml

images:
- name: yny.ocir.io/ax1dvc8vmenm/discord-bot
  newTag: 91dc49237f031e49340919011fd187e9efc88bf7
