apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: slack-viz
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: slack-viz-prod
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/slack-viz-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
