apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-viz-app
  labels:
    app: slack-viz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack-viz-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: slack-viz-app
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - image: yny.ocir.io/ax1dvc8vmenm/slack-view:3
        name: app
        ports:
        - containerPort: 3000
        env:
        - name: NUXT_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: slack-viz-prod
              key: NUXT_MONGODB_URI
        - name: NUXT_PUBLIC_DEMO_WORKSPACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-viz-prod
              key: NUXT_DEMO_WORKSPACE_TOKEN
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: slack-viz-app
spec:
  type: ClusterIP
  selector:
    app: slack-viz-app
  ports:
  - port: 80
    targetPort: 3000
