apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-viz-prod
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: slack-viz-prod
    creationPolicy: Owner
    template:
      data:
        MONGO_ROOT_PASSWORD: '{{ .raw | fromJson | dig "mongodb-root-password" "" }}'
        NUXT_MONGODB_URI: '{{ .raw | fromJson | dig "nuxt-mongodb-uri" "" }}'
        GITHUB_CLIENT_ID: '{{ .raw | fromJson | dig "github-client-id" "" }}'
        GITHUB_CLIENT_SECRET: '{{ .raw | fromJson | dig "github-client-secret" "" }}'
        OAUTH2_PROXY_COOKIE_SECRET: '{{ .raw | fromJson | dig "oauth2-proxy-cookie-secret" "" }}'
        NUXT_DEMO_WORKSPACE_TOKEN: '{{ .raw | fromJson | dig "nuxt-demo-workspace-token" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: slack-viz-prod
