apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- wacruit-judge-server.yaml
- wacruit-judge-worker.yaml
- wacruit-server.yaml

images:
- name: yny.ocir.io/ax1dvc8vmenm/wacruit-dev/wacruit-judge-server
  newTag: "28"
- name: yny.ocir.io/ax1dvc8vmenm/wacruit-dev/wacruit-server
  newTag: "147"
