apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-server
  labels:
    app: account-server
spec:
  replicas: 0
  selector:
    matchLabels:
      app: account-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: account-server
    spec:
      serviceAccountName: sso
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - image: yny.ocir.io/ax1dvc8vmenm/sso-prod/account-server:2
          name: account-server
          resources:
            requests:
              cpu: 100m
              memory: 288Mi
            limits:
              memory: 288Mi
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Duser.timezone=UTC"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sso
imagePullSecrets:
  - name: ocir-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: account-server
spec:
  type: ClusterIP
  selector:
    app: account-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: account-server
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - account-api.wafflestudio.com
  http:
    - match:
        - uri:
            exact: /docs/index.html
      route:
        - destination:
            host: account-server
