apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-base
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].failurePolicy
    - .webhooks[].clientConfig.caBundle
  destination:
    name: in-cluster
    namespace: istio-system
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.26.0
