apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-util
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: istio-util
  destination:
    name: in-cluster
    namespace: istio-ingress
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/istio-util
    directory:
      include: 'istio-util-*.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
