apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airbnb-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: airbnb-dev
    creationPolicy: Owner
    template:
      data:
        SPRING_DATASOURCE_URL: '{{ .raw | fromJson | dig "spring.datasource.url" "" }}'
        SPRING_DATASOURCE_USERNAME: '{{ .raw | fromJson | dig "spring.datasource.username" "" }}'
        SPRING_DATASOURCE_PASSWORD: '{{ .raw | fromJson | dig "spring.datasource.password" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: airbnb-dev
