apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  destination:
    name: in-cluster
    namespace: argocd
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.6.4
    chart: argo-cd
    helm:
      valueFiles:
      - $values/argocd/argocd/values.yaml
  - repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    ref: values
