configs:
  cm:
    admin.enabled: true
    exec.enabled: true
    timeout.reconciliation: 15s
    url: https://argocd-oci.wafflestudio.com
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23linI41QdwlV1zULW
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: wafflestudio
  params:
    server.insecure: true
  rbac:
    policy.csv: |
      g, wafflestudio:waffle-k8s-admin, role:waffle-k8s-admin
      g, wafflestudio:snutt-server, role:snutt-server
      p, role:waffle-k8s-admin, applications, *, */*, allow
      p, role:waffle-k8s-admin, clusters, get, *, allow
      p, role:waffle-k8s-admin, projects, *, *, allow
      p, role:waffle-k8s-admin, repositories, get, *, allow
      p, role:waffle-k8s-admin, repositories, create, *, allow
      p, role:waffle-k8s-admin, repositories, update, *, allow
      p, role:waffle-k8s-admin, repositories, delete, *, allow
      p, role:waffle-k8s-admin, exec, create, */*, allow
      p, role:snutt-server, projects, get, snutt, allow
      p, role:snutt-server, applications, *, snutt/*, allow
      p, role:snutt-server, exec, create, snutt/*, allow
      g, wafflestudio:moiming, role:moiming-server
      p, role:moiming-server, projects, get, moiming, allow
      p, role:moiming-server, applications, *, moiming/*, allow
      p, role:moiming-server, exec, create, moiming/*, allow

    policy.default: role:readonly

dex:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

applicationSet:
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

controller:
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi

notifications:
  cm:
    service.webhook.pupuri-bot: |
      url: https://pupuri-api.wafflestudio.com/argocd/webhook-endpoint
      method: POST
      headers:
        - name: Content-Type
          value: application/json
    templates.sync-completed: |-
      {"namespace":"{{.app.metadata.namespace}}","app":"{{.app.metadata.name}}"}
    triggers.sync-completed: |-
      - description: Application sync completed
        oncePer: app
        when: app.status.operationState.phase in ['Succeeded']
        send:
          - webhook:pupuri-bot
    subscriptions.sync-completed: |-
      recipients:
        - pupuri-bot
    controller.disableAnnotations: "true"
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

redis:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 64Mi

repoServer:
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi

server:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: istio-util
    spec:
      description: Project for istio-util applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: pupuri
    spec:
      description: Project for pupuri applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: siksha
    spec:
      description: Project for siksha applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: snutt
    spec:
      description: Project for snutt applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: truffle
    spec:
      description: Project for truffle applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: wacruit
    spec:
      description: Project for wacruit applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: waffledotcom
    spec:
      description: Project for waffledotcom applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: allclear
    spec:
      description: Project for allclear applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: moiming
    spec:
      description: Project for moiming applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: snuclear
    spec:
      description: Project for snuclear applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: pecan
    spec:
      description: Project for pecan applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      namespace: argocd
      name: hangsha
    spec:
      description: Project for hangsha applications
      sourceRepos:
      - '*'
      destinations:
      - namespace: '*'
        server: '*'
      sourceNamespaces:
      - argocd
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
