apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: telepresence
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: mutator-webhook-tls
    namespace: telepresence
    jqPathExpressions:
    - .data
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: agent-injector-webhook-telepresence
    jqPathExpressions:
    - .webhooks[].clientConfig.caBundle
  destination:
    name: in-cluster
    namespace: telepresence
  sources:
  - repoURL: ghcr.io/telepresenceio
    chart: telepresence-oss
    targetRevision: 2.27.0
    helm:
      releaseName: traffic-manager
      valueFiles:
      - $values/argocd/telepresence/values.yaml
  - repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
