apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: moiming-prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: moiming
  destination:
    name: in-cluster
    namespace: moiming-prod
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/moiming-prod
    directory:
      include: 'moiming-*.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
