apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: truffle
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: truffle
  destination:
    name: in-cluster
    namespace: truffle-prod
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/truffle-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
