apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truffle-prod
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: truffle-prod
    creationPolicy: Owner
    template:
      data:
        SECURITY_KEY: '{{ .raw | fromJson | dig "SECURITY_KEY" "" }}'
        SPRING_PROFILES_ACTIVE: '{{ .raw | fromJson | dig "SPRING_PROFILES_ACTIVE" "" }}'
        SPRING_R2DBC_URL: '{{ .raw | fromJson | dig "SPRING_R2DBC_URL" "" }}'
        SPRING_R2DBC_USERNAME: '{{ .raw | fromJson | dig "SPRING_R2DBC_USERNAME" "" }}'
        SPRING_R2DBC_PASSWORD: '{{ .raw | fromJson | dig "SPRING_R2DBC_PASSWORD" "" }}'
        TRANSPORT_SLACK_ENABLED: '{{ .raw | fromJson | dig "TRANSPORT_SLACK_ENABLED" "" }}'
        TRANSPORT_SLACK_TOKEN: '{{ .raw | fromJson | dig "TRANSPORT_SLACK_TOKEN" "" }}'
  data:
    - secretKey: raw
      remoteRef:
        key: truffle-prod
