apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- allclear-db.yaml
- allclear-secret.yaml
- allclear-valkey.yaml
- allclear-web.yaml

images:
- name: yny.ocir.io/ax1dvc8vmenm/allclear-dev/allclear-web
  newTag: 33578240954-1
