apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: snutt-timetable-prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: snutt-prod
  source:
    repoURL: https://github.com/wafflestudio/waffle-world-oci.git
    targetRevision: main
    path: argocd/snutt-prod/snutt-timetable
    directory:
      include: 'resources.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
