apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-ev-batch-lecture-sync-latest-semester
  labels:
    app: snutt-ev-batch-lecture-sync-latest-semester
spec:
  concurrencyPolicy: Forbid
  schedule: "10 */12 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: snutt-ev-batch-dev
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-ev-batch:40
              name: snutt-ev-batch-lecture-sync-latest-semester
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 2Gi
              env:
                - name: JOB_NAME
                  value: "NEXT_SEMESTER_SYNC_JOB"
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
                - name: TRUFFLE_ENABLED
                  value: "true"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-ev-batch-lecture-sync-all
  labels:
    app: snutt-ev-batch-lecture-sync-all
spec:
  concurrencyPolicy: Forbid
  # 실행 방법
  # kubectl create job snutt-ev-batch-snuev-migration --from=cronjob/snutt-ev-batch-snuev-migration
  schedule: "0 0 31 2 *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: snutt-ev-batch-dev
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-ev-batch:40
              name: snutt-ev-batch-lecture-sync-all
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 2Gi
              env:
                - name: JOB_NAME
                  value: "SYNC_JOB"
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
                - name: TRUFFLE_ENABLED
                  value: "true"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: snutt-ev-batch-snuev-migration
  labels:
    app: snutt-ev-batch-snuev-migration
spec:
  concurrencyPolicy: Forbid
  suspend: true
  # 실행 방법
  # kubectl create job snutt-ev-batch-snuev-migration --from=cronjob/snutt-ev-batch-snuev-migration
  schedule: "0 0 31 2 *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          restartPolicy: OnFailure
          serviceAccountName: snutt-ev-batch-dev
          containers:
            - image: yny.ocir.io/ax1dvc8vmenm/snutt-dev/snutt-ev-batch:40
              imagePullPolicy: IfNotPresent
              name: snutt-ev-batch-snuev-migration
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 200m
                  memory: 2Gi
              env:
                - name: JOB_NAME
                  value: "SNUEV_MIGRATION_JOB"
                - name: SPRING_PROFILES_ACTIVE
                  value: "dev"
                - name: TRUFFLE_ENABLED
                  value: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snutt-ev-batch-dev
