apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wafflestudio@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-2
          hostedZoneID: Z04088332GMJ43MZ59UNN
          accessKeyID: AKIAV5APOORJFOLSRLG3
          secretAccessKeySecretRef:
            name: aws-route53-credentials
            key: secret-access-key
