apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: istio-util
spec:
  description: Project for istio-util applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: pupuri
spec:
  description: Project for pupuri applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: siksha
spec:
  description: Project for siksha applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: snutt
spec:
  description: Project for snutt applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: truffle
spec:
  description: Project for truffle applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: wacruit
spec:
  description: Project for wacruit applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: waffledotcom
spec:
  description: Project for waffledotcom applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: allclear
spec:
  description: Project for allclear applications
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'