apiVersion: apps/v1
kind: Deployment
metadata:
  name: snuclear-server
  labels:
    app: snuclear-server
spec:
  # replicas: HPA
  selector:
    matchLabels:
      app: snuclear-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        app: snuclear-server
    spec:
      serviceAccountName: snuclear-server-prod
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - image: yny.ocir.io/ax1dvc8vmenm/snuclear-prod/snuclear-server:34
          name: snuclear-server
          resources:
            requests:
              cpu: 50m
              memory: 384Mi
            limits:
              memory: 768Mi
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            timeoutSeconds: 3
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            failureThreshold: 20
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: snuclear-server-hpa
  labels:
    app: snuclear-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: snuclear-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snuclear-server-prod
---
apiVersion: v1
kind: Service
metadata:
  name: snuclear-server
spec:
  type: ClusterIP
  selector:
    app: snuclear-server
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: snuclear-server
spec:
  gateways:
    - istio-ingress/waffle-ingressgateway
    - mesh
  hosts:
    - snuclear-server.wafflestudio.com
  http:
    - route:
        - destination:
            host: snuclear-server
      headers:
        request:
          set:
            X-Forwarded-Proto: "https"
